# the name of your track or event
name = "Filecoin Network Analytics Day"

# the name of the group organizing the event
org = "Starboard"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "sylvan"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = ""

# the start date of the event
date = "Monday October 31st 2022"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "15:00 - 20:00 (3:00 PM - 8:00 PM Western European Time - Lisbon)"

# the event venue name (will show up on the event card - TODO)
venueName = "Brotéria, Rua de São Pedro de Alcântara, Lisboa, Portugal"

# the event venue address (will show up on a map -- TODO)
venueAddress = "Brotéria, Rua de São Pedro de Alcântara, Lisboa, Portugal"

# the max number of attendees of the event
attendees = "All Welcome"


# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the event.
# will show up when the user clicks the event card.
description = "Description:
               Join us as we dive into the network analytics that continuously spark conversations and inform network’s decisions.
               On the Filecoin Network Analytics Day, you will hear insightful talks and discussions covering important topics on Filecoin network analytics, including:
               The importance of network analytics to Web3 governance and improvement
               Conducting effective network analytics for Filecoin - what's needed?
               Demystifying Filecoin circulating supply
               Analyzing key health metrics of Filecoin
               Storage provider reputation analytics
               And more..."

# the priority in the schedule table, leave commented if you don't need to control this
# 1 will appear at the top, higher numbers appear closer to bottom
# priority = 1
